### ISSUE TITLE
Question: Is schema.json absolutely necessary?

### ISSUE THREAD

**Issue by capaj** [helios1138/graphql-typed-client#7]
I tried to generate the client for our schema at @LeapLabs and the json is pretty big- around 270 Kb.
Is this JSON necessary?
I guess the library generates the GQL query based on it, so it most likely is. It just seems like it's not going to work well for large and complex APIs if you have to load up hundred of kilobytes of JSON just to do a small query.

**Comment by helios1138** [comment]
- the exact structure is going to be changed in the refactoring I'm working on right now
- the size of JSON file itself shouldn't really matter, as it is loaded and processed only once, more important is the memory footprint and access speed
  - of course, then there is a balance to strike between those two
- I'll look into the possibility of having queries being pre-constructed so that resolution happens only once, then you just call it with variables
